name: sugar_cosmetics_instagram_analytics
version: '1.0'
config-version: 2

profile: sugar_cosmetics_instagram_analytics

model-paths:
  - sugar_cosmetics_instagram_analytics_model

test-paths:
  - sugar_cosmetics_instagram_analytics_tests

seed-paths: 
  - sugar_cosmetics_instagram_analytics_seed

seeds:
    +schema: raw_instagram